---

- name: Get kernel version
  shell: "uname -r"
  register: vbox_additions_kernel_version
  changed_when: false
  tags:
    - vbox_additions_check

- name: Check if Additions are already installed in the right version
  shell: >
    test -f /lib/modules/{{ vbox_additions_kernel_version.stdout }}/misc/vboxguest.ko &&
    source /var/lib/VBoxGuestAdditions/config &&
    [[ "{{ vbox_additions_version }}" == "$INSTALL_VER" ]]
  register: vbox_additions_installed
  when: not vbox_additions_build_force
  changed_when: false
  failed_when: false
  tags:
    - vbox_additions_check

- block:

  - name: Download ISO
    get_url:
      url: "{{ vbox_additions_iso_url }}"
      dest: "{{ vbox_additions_iso_path }}"
    when: >
      vbox_additions_iso_local | length == 0
    tags:
      - vbox_additions_iso

  - name: Copy ISO
    copy:
      src: "{{ vbox_additions_iso_local }}"
      dest: /tmp/VBoxGuestAdditions_{{ vbox_additions_version }}.iso
    when: >
      vbox_additions_iso_local | length > 0
    tags:
      - vbox_additions_iso

  - name: Mount ISO
    shell: env mount /tmp/VBoxGuestAdditions_{{ vbox_additions_version }}.iso /mnt -t iso9660 -o loop
    tags:
      - vbox_additions_iso

  - name: Install build dependencies
    package:
      name: "{{ (item + '-' + vbox_additions_kernel_version.stdout) if item == 'kernel-devel' else item }}"
    with_items: "{{ vbox_additions_build_deps }}"
    tags:
      - vbox_additions_pkg

  - name: Build modules
    shell: KERN_DIR=/usr/src/kernels/{{ vbox_additions_kernel_version.stdout }} /mnt/VBoxLinuxAdditions.run
    register: vbox_additions_build_result
    failed_when: (false if vbox_additions_build_ignore_errors else (vbox_additions_build_result.rc != 0))
    tags:
      - vbox_additions_build

  - name: Umount ISO
    mount:
      name: /mnt
      src: /tmp/VBoxGuestAdditions_{{ vbox_additions_version }}.iso
      fstype: iso9660
      state: unmounted
    tags:
      - vbox_additions_iso

  - name: Remove ISO
    file:
      path: "{{ vbox_additions_iso_path }}"
      state: absent
    when: >
      vbox_additions_iso_remove
    tags:
      - vbox_additions_iso

  - name: Uninstall build dependencies (RedHat)
    shell: env yum remove --assumeyes --setopt=clean_requirements_on_remove=1 {{ item }}
    when: >
      ansible_facts.os_family == "RedHat" and
      vbox_additions_build_deps_uninstall and
      item != "kernel"
    with_items: "{{ vbox_additions_build_deps }}"
    tags:
      - vbox_additions_pkg

  - name: Uninstall build dependencies (Other)
    package:
      name: "{{ item }}"
      state: absent
    when: >
      ansible_facts.os_family != "RedHat" and
      vbox_additions_build_deps_uninstall and
      item != "kernel"
    with_items: "{{ vbox_additions_build_deps }}"
    tags:
      - vbox_additions_pkg

  when: >
    (
      vbox_additions_installed is defined and
      vbox_additions_installed.rc != 0
    ) or
    vbox_additions_build_force
